autoload -U compinit; compinit

# -----------------------------------
# Powerlevel10k
# -----------------------------------
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# -----------------------------------
# PATH
# -----------------------------------
local code_dir=$HOME/code
local homebrew_dir=$HOME/bin/homebrew
local cloudsdk_dir=$HOME/code/google-cloud-sdk

# PATH precedence (first = highest priority):
export PATH="\
$HOME/.local/bin:\
$code_dir/bin:\
$cloudsdk_dir/bin:\
$HOME/go/current/bin:\
$code_dir/gotip/bin:\
$HOME/go/bin:\
$HOME/.cargo/bin:\
$HOME/Library/Python/3.11/bin:\
$homebrew_dir/bin:\
$homebrew_dir/sbin:\
$homebrew_dir/opt/fzf/bin:\
$PATH"

# -----------------------------------
# Sourced Configs
# -----------------------------------
source $homebrew_dir/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $homebrew_dir/share/zsh-history-substring-search/zsh-history-substring-search.zsh

# Custom dotfiles
local dotfiles_dir=$code_dir/dotfiles
source $dotfiles_dir/powerlevel10k/powerlevel10k.zsh-theme
source $dotfiles_dir/config/aliases.conf
[[ ! -f $HOME/.fzf.zsh ]] || source $HOME/.fzf.zsh

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  alias pbcopy="xsel — clipboard — input"
  alias pbpaste="xsel — clipboard — output"
fi

# Google Cloud SDK completion
if [ -f "$cloudsdk_dir/completion.zsh.inc" ]; then . "$cloudsdk_dir/completion.zsh.inc"; fi
